### ISSUE TITLE
Openweathermap by using openlayer3

### ISSUE THREAD

**Issue by holimatic** [buche/leaflet-openweathermap#11]
Hi Buche,
I like your leaflet-openweathermap very much but unfortunately it works only with leaflet as the name says. However I would like to have it for openlayer3. I try several things but I was not able to make it work. I just need the current data for cities and stations.
Could you help me to integrate it in openlayer3 as well? Maybe it's a good issue to have it on both libraries. On the other hand I could help to translate into german.
Guido

**Comment by buche** [comment]
Hi Guido,

some years ago I've done some simple maps with OpenLayers (maybe v1). Therefore I know it is pretty different to Leaflet. As I don't have the time to look deeply into OL3 you're on your own. OpenWeatherMap published some code for OpenLayers, maybe this will give you an start.

Translating to German is no problem (außer du kennst dich mit den metereologischen Begriffen gut aus - just send in some Pull Requests).

Good luck and have fun,
Buche
