### ISSUE TITLE
register in bower

### ISSUE THREAD

**Issue by george-silva** [buche/leaflet-openweathermap#18]
Hello @buche! Great package.

I saw that it's not registered in bower. Can you register it?

I'd rather not have to fork and register it.

Thanks!

**Comment by buche** [comment]
I don't have any clue about bower. Just add a pull request, please.

**Comment by george-silva** [comment]
Hey buche!

To register in bower we need to use the command line. I can register the package for you if needed.

Check this:

http://bower.io/docs/creating-packages/#register

It's pretty easy to do and I'd rather have you, the author, register it. The first step is already there, the bower.json file. We just need to publish it.

**Comment by george-silva** [comment]
@buche it looks like I can register this, without owning this repo. I'll register. If there's any "string's attached", I'll forward them to you.

**Comment by george-silva** [comment]
@buche here's the final info. leaflet-openweathermap is registered!

```bash
bower register leaflet-openweathermap https://github.com/buche/leaflet-openweathermap.git
bower resolve       https://github.com/buche/leaflet-openweathermap.git#*
bower checkout      leaflet-openweathermap#master
bower resolved      https://github.com/buche/leaflet-openweathermap.git#5f9bd72076
? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
bower register      https://github.com/buche/leaflet-openweathermap.git

Package leaflet-openweathermap registered successfully!
All valid semver tags on https://github.com/buche/leaflet-openweathermap.git will be available as versions.
To publish a new version, just release a valid semver tag.

Run bower info leaflet-openweathermap to list the available versions.
```

**Comment by buche** [comment]
@george-silva Thanks for your effort!

**Comment by george-silva** [comment]
@buche no problem. Now leaflet-openweathermap can be installed with bower, using:

```bash
cd project_dir
bower install leaflet-openweathermap
```

Provided that:

1. You have bower installed;
1. Your project is configured to use bower;
