### ISSUE TITLE
Demo Site Unavailable

### ISSUE THREAD

**Issue by samseen** [buche/leaflet-openweathermap#19]
The Demo [Site](http://openweathermap.map.comlu.com/) is actually not available. Where else can users see how it works as a demo?

**Comment by buche** [comment]
This link is an alias to http://map.comlu.com/openweathermap/ which you can use, too. Sometimes some robots are doing some mass requests for one of this addresses then the free hoster blocks access for some days. But, hey, it's a free service used by me for some demo pages only.

I hope the other address will work for you. If not just download the project as zip, unzip it, and there's the folder named "example". Load "index.html" in your browser and you get your own and local leaflet-openweathermap.
