### ISSUE TITLE
No Data is displayed on map.

### ISSUE THREAD

**Issue by tvjmohan** [buche/leaflet-openweathermap#22]
hi,

 i am using this application from 2 years. but this time i seen that map is not showing any data. No check box is showing data. 

![image](https://cloud.githubusercontent.com/assets/414051/24832534/c52a47ee-1ccf-11e7-9d7e-caf1293c20fe.png)

in console i can see error.

![image](https://cloud.githubusercontent.com/assets/414051/24832573/3aeaf0a0-1cd0-11e7-86ff-68fb746a13c1.png)

but i can see responce from openweather map.  

![image](https://cloud.githubusercontent.com/assets/414051/24832593/5836e902-1cd0-11e7-9574-51b0cb147318.png)

please help me to solve this.

**Comment by buche** [comment]
I've got many problems receiving tiles from OWM, but because of timeouts on OWM's side. BUt having an invalit LatLng object is new to me. I'll investigate on this, but be patient, please.

**Comment by tvjmohan** [comment]
HI buche,  Thank you for your reply. 

![image](https://cloud.githubusercontent.com/assets/414051/25009003/e7b38c6a-2082-11e7-81e1-bd79b1c3b1ac.png)
in the above path **leaflet.js**  in this file.         

at lines 

"if (t = parseFloat(t), e = parseFloat(e), isNaN(t) || isNaN(e)) 
throw new Error("Invalid LatLng object: (" + t + ", " + e + ")");
"
we are getting last 2 variables as undefined, undefined.     t and  e  are coming as undefined. 

for this reason its is going to "INVALID LATLAN OBJECT:(....."    

i tried to resolve this many ways,  but not able to get it fixed.  

Hope you will come up with solution ,  Thank you.

**Comment by buche** [comment]
That's the leaflet library from https://github.com/Leaflet/Leaflet
I'll update it to the newest version in a few days. Maybe this helps.

**Comment by buche** [comment]
Just released v1.0.4:
OWM now needs an AppId even for tile layers and OWM changed attribute name for coordinates.

Please check if it works again for you.

**Comment by tvjmohan** [comment]
I have used APPID  every where in the tiles.   but where i have to change the coordinates ?    which file  and what is the new attribute name ??????? plz help me.... this is pending from April.  2017
