### ISSUE TITLE
property 'call', 'removeControl'  of undefined Leaflet 1.0.3

### ISSUE THREAD

**Issue by drunkod** [buche/leaflet-openweathermap#23]
leaflet.js:6 Uncaught TypeError: Cannot read property 'call' of undefined
    at e.whenReady (leaflet.js:6)
    at e.addLayer (leaflet.js:6)
    at e._onInputClick (leaflet.js:9)
    at HTMLInputElement.h (leaflet.js:6)

leaflet-openweathermap.js:319 Uncaught TypeError: Cannot read property 'removeControl' of null
    at e.onRemove (leaflet-openweathermap.js:319)
    at e.removeLayer (leaflet.js:6)
    at e._onInputClick (leaflet.js:9)
    at HTMLInputElement.h (leaflet.js:6)

**Comment by buche** [comment]
Do you have more information WHEN this happens? What have you done to get get this error? Can you reproduce it?

**Comment by Dimm38Rus** [comment]
Have same problem, error occurs when trying to choose weather overlay. Leaflet 1.0.3.
Fixed by replacing L.OWM.Current = L.Class.extend to L.OWM.Current = L.Layer.extend

**Comment by buche** [comment]
ok, you're using Leaflet 1.0.3. Haven't updated Leaflet myself, yet. Will look into it in about three weeks 'cause I'vo got no time now.

**Comment by buche** [comment]
I'm updating the example to leaflet 1.2.0 and adapting my code to it.
