### ISSUE TITLE
default map, level tile , current weather on load

### ISSUE THREAD

**Issue by maxservice** [buche/leaflet-openweathermap#31]
Is it possibile to set default map, level tile and current weather on load map?

Thanks

**Comment by buche** [comment]
This is nothing the plugin can realize. If you write your own map using this plugin you can set any map attributes as you like. Remember: This is just a plugin for people creating leaflet based maps.

The demo map in the examples directory is just that: a demo. It is not intended for production use used by other people. Its data plan on getting OpenWeatherMap's data is very limited (and is often exceeded).

**Comment by maxservice** [comment]
Thank you for your answer, i'm not doing anything as you said, i'm only
improving my know-how and anyway  i solved myself what i was looking for.

As soon as possible i will pull the request for the
leaflet-openweathermap.js file with the italian translation.

Best Regards

Max

2018-05-08 19:47 GMT+02:00 buche <notifications@github.com>:
