### ISSUE TITLE
current weather (city/station) and wind rose non-functional

### ISSUE THREAD

**Issue by rookiepsu** [buche/leaflet-openweathermap#9]
Approx 2 weeks ago this stopped working.  Anytime I try now, it comes back with a "syntax error - unexpected character:"

**Comment by buche** [comment]
This is not an issue of leaflet-openweathermap, but an issue of openweathermap itself. The data delivered by OpenWeatherMap seems to be corrupt. OpenWeatherMap's own map at http://openweathermap.org/maps is affected, too.

Please report it at http://openweathermap.org/

Sorry that I cannot help.

**Comment by buche** [comment]
Cannot fix it, sorry. It's up to OWM.
